### ISSUE TITLE
Create a Wishlist page

### ISSUE THREAD

**Issue by saif520** [saif520/Chenab-Pointer-011#19]
![image](https://github.com/saif520/Chenab-Pointer-011/assets/62957608/d3dd764c-29f8-4434-954d-ad6373e157a9)

- [x] Create UI 
- [x] fetch data from local storage
- [x] create cards for the products 
- [x] create button with add to cart functionality which will remove products from wishlist and add it to carts

**Comment by mohammadtehreem** [comment]
Moving items from wishlist data to cart data in local storage
