### ISSUE TITLE
Create card for cart page

### ISSUE THREAD

**Issue by saif520** [saif520/Chenab-Pointer-011#20]
![image](https://github.com/saif520/Chenab-Pointer-011/assets/62957608/c2cdfe0e-6978-41ca-8d10-c67d40335120)

- [x] fetch data from local storage 
- [x] create cards for data
- [x] create remove from cart and move to wishlist button with moving functioinalities
- [ ] show wishlist items att the bottom of cart items

**Comment by mohammadtehreem** [comment]
Didn't add the wishlist items to be displayed in cart
