### ISSUE TITLE
Create cart value section 

### ISSUE THREAD

**Issue by saif520** [saif520/Chenab-Pointer-011#21]
![image](https://github.com/saif520/Chenab-Pointer-011/assets/62957608/1aa07711-701b-48d9-8545-32a74d4a1039)

- [x] create a section as per the image
- [x] show total price 
- [x] show discounted price
- [x] Add a button with a form for adding the address
- [x] In the address form add a button to place an order
- [x] remove products from cart after placing orders

**Comment by mohammadtehreem** [comment]
Displaying a form for adding address, and clearing cart after placing order
