### ISSUE TITLE
Create a login page

### ISSUE THREAD

**Issue by saif520** [saif520/Chenab-Pointer-011#22]
![image](https://github.com/saif520/Chenab-Pointer-011/assets/62957608/49ce3b89-f418-4d9a-b731-4635e293b94c)

- [x] Create UI for login page
- [x] create login and sing up form
- [x] check is user is present if present ask them to login
- [x] on sign up store users credentials on server

**Comment by mohammadtehreem** [comment]
Done login page, stored users data in db,json
